[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps 2>&1 && npx prisma generate 2>&1 && npm run build 2>&1"
watchPatterns = ["src/**", "package.json"]

[deploy]
startCommand = "npm run start 2>&1"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
